<div style="background-color: #90A8A5; padding: 10px; height: 100px; border-radius: 15px; position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Second-Year Engineering Student</span>

<div style="background-color:#232023; padding: 10px;border-radius: 15px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Artificial Intelligence/Machine Learning UpSkills Notebook <br> 
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">From Basics to Real-World — Starts Your ML Journey</h3></div>

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Agenda — Pandas 
</h3> </div>

### What you'll learn:
- Pandas Introduction
- Series
- DataFrame
- Reading and Writing Data
- Data Selection and Filtering
- Data Cleaning
- Sorting and Grouping
- Exporting Data

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>What is Pandas ? 
</h3> </div>

Pandas is a **Python library** used for **data manipulation** and **analysis**.  
It works with **structured data** like tables (rows & columns).

In [1]:
# Importing Pandas library
import pandas as pd

# Checking Pandas version
print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.3

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2> Pandas Series
</h3> </div>

A **Series** is a **1-dimensional labeled array**.  
It can hold data of any type (integer, string, float, etc.).

**Syntax:** <br>
pd.Series(data, index)

In [2]:
# Creating a Series from a list
data = [10, 20, 30, 40]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
# Creating a Series with custom index
s_custom = pd.Series(data, index=['A', 'B', 'C', 'D'])
print("Series with Custom Index:")
print(s_custom)

Series with Custom Index:
A    10
B    20
C    30
D    40
dtype: int64

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Pandas DataFrame
</h3> </div>

 A **DataFrame** is a **2-dimensional table** with rows and columns.  
It can be created from:
- Lists
- Dictionaries
- NumPy arrays
- CSV/Excel files

**Syntax:**<br>
pd.DataFrame(data)

In [4]:
# Creating a DataFrame from a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22],
    'City': ['Delhi', 'Mumbai', 'Kolkata']
}

df = pd.DataFrame(data)
df

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   22  Kolkata

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Reading Data
</h3> </div>

Pandas can read data from various sources:
- CSV → `pd.read_csv('file.csv')`
- Excel → `pd.read_excel('file.xlsx')`
- JSON → `pd.read_json('file.json')`

In [5]:
# Example: Reading from CSV (replace 'data.csv' with your file)
# df_csv = pd.read_csv('data.csv')
# df_csv.head()

# For demonstration, let's create a sample DataFrame
sample_data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard'],
    'Price': [80000, 500, 1500]
}
df_sample = pd.DataFrame(sample_data)
df_sample

    Product  Price
0    Laptop  80000
1     Mouse    500
2  Keyboard   1500

In [6]:
df = pd.read_csv('airlines_flights_data.csv')
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Exploring Data
</h3> </div>

### Common functions:
- `df.head()` → First 5 rows
- `df.tail()` → Last 5 rows
- `df.shape` → Dimensions (rows, columns)
- `df.info()` → Column data types & memory usage
- `df.describe()` → Statistical summary

In [7]:
df.head()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [8]:
df.tail()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [9]:
print("Shape:", df.shape)

Shape: (300153, 12)

In [10]:
 print("\nInfo:",df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

Info: None

In [11]:
print("\nSummary Statistics:",df.describe())

Summary Statistics:                index       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Selecting Data
</h3> </div>

### Selecting columns:

In [12]:
# Select a single column
df['airline']

0         SpiceJet
1         SpiceJet
2          AirAsia
3          Vistara
4          Vistara
            ...
300148     Vistara
300149     Vistara
300150     Vistara
300151     Vistara
300152     Vistara
Name: airline, Length: 300153, dtype: object

In [13]:
# Select multiple columns
df[['airline', 'flight']]

         airline   flight
0       SpiceJet  SG-8709
1       SpiceJet  SG-8157
2        AirAsia   I5-764
3        Vistara   UK-995
4        Vistara   UK-963
...          ...      ...
300148   Vistara   UK-822
300149   Vistara   UK-826
300150   Vistara   UK-832
300151   Vistara   UK-828
300152   Vistara   UK-822

[300153 rows x 2 columns]

In [14]:
# Selecting a single row by index label
print(df.loc[0])

index                      0
airline             SpiceJet
flight               SG-8709
source_city            Delhi
departure_time       Evening
stops                   zero
arrival_time           Night
destination_city      Mumbai
class                Economy
duration                2.17
days_left                  1
price                   5953
Name: 0, dtype: object

In [15]:
print(df.loc[1])

index                           1
airline                  SpiceJet
flight                    SG-8157
source_city                 Delhi
departure_time      Early_Morning
stops                        zero
arrival_time              Morning
destination_city           Mumbai
class                     Economy
duration                     2.33
days_left                       1
price                        5953
Name: 1, dtype: object

In [16]:
# Selecting a single row by position
print(df.iloc[1])

index                           1
airline                  SpiceJet
flight                    SG-8157
source_city                 Delhi
departure_time      Early_Morning
stops                        zero
arrival_time              Morning
destination_city           Mumbai
class                     Economy
duration                     2.33
days_left                       1
price                        5953
Name: 1, dtype: object

<div style="background-color: #DCECE9; color: black; padding: 4px;border-radius: 10px; text-align: center;">
    <h2>Filtering Data
</h3> </div>

In [17]:
import pandas as pd
df = pd.read_csv("airlines_flights_data.csv")
# Flights by specific airline
df[df['airline'] == "Air_India"]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
16,16,Air_India,AI-887,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.08,1,5955
17,17,Air_India,AI-665,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955
23,23,Air_India,AI-441,Delhi,Evening,one,Night,Mumbai,Economy,3.75,1,5955
37,37,Air_India,AI-453,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,8.83,1,11900
40,40,Air_India,AI-504,Delhi,Night,one,Morning,Mumbai,Economy,11.00,1,12150
...,...,...,...,...,...,...,...,...,...,...,...,...
300143,300143,Air_India,AI-440,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.42,49,51345
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345
300146,300146,Air_India,AI-440,Chennai,Early_Morning,one,Morning,Hyderabad,Business,26.83,49,51345
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739

In [18]:
# Flights with arrival_time NOT equal to "Morning" and NOT equal to "Early_Morning"
df[(df['arrival_time'] != "Morning") & (df['arrival_time'] != "Early_Morning")]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585