<div style="background-color: #90A8A5; padding: 10px; height: 100px;  position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>

<div style="background-color:#232023; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Artificial Intelligence/Machine Learning UpSkills Notebook <br> 
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">From Basics to Real-World — Starts Your ML Journey</h3></div>

## Reading Data from different types of files ##

In [2]:
# Importing the pandas library as pd
import pandas as pd

In [3]:
# Read data from csv file
data = pd.read_csv("house_prices.csv")
# Read data  from excel file
# data = pd.read_excel("file_name")
# Read data from json file
# data = pd.read_json("file_name")

In [4]:
data

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,N,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,N,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,N,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,N,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,N,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,N,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,N,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,N,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,N,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,N,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

### Creating DataFrames ###

In [5]:
data1 = {
    "Name" : ["Trisha" , "Shivam" , "Radhika" , "Madhav"],
    "Age" : [10,20,30,40],
    "City" : ["Nagpur","mumbai" , "Barsana" , "Gokul"]
}
df = pd.DataFrame(data1)

In [6]:
print(df)

      Name  Age     City
0   Trisha   10   Nagpur
1   Shivam   20   mumbai
2  Radhika   30  Barsana
3   Madhav   40    Gokul

In [7]:
df

      Name  Age     City
0   Trisha   10   Nagpur
1   Shivam   20   mumbai
2  Radhika   30  Barsana
3   Madhav   40    Gokul

### Saving the Created DataFrame in the files ###

In [8]:
df.to_csv("Output.csv")
# df.to_excel(Output.xlsx")
# df.to_json(Output.json")

## Exploring the Dataset ##

In [9]:
print("Display 10 rows of first")
data.head()

Display 10 rows of first

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,N,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,N,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,N,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,N,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,N,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [10]:
print("Display 10 rows of last")
data.tail()

Display 10 rows of last

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,N,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,N,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,N,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,N,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,N,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

## Understanding the Data ##
### info() Method
We use **info()** method to understand the data

In [11]:
print("Displaying the information of Dataset :")
data.info()

Displaying the information of Dataset :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  object
 9   view           21613 non-null  int64
 10  condition      21613 non-null  object
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(13), object(3)
memory usage: 3.5+ MB

In [12]:
print("Displaying the information of DataFrame :")
df.info()

Displaying the information of DataFrame :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

## Describe() Method ##
It is used for the quick summary of the Data.
This method gives the descriptive statistic summary of the data.

In [13]:
data.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.234303,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.766318,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,4.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

### shape and Columns ###
It answer the two questions.
1. How big is your data.<br>
2. What are the names of columns present in the data .

In [16]:
print(f"Shape : {data.shape}")

Shape : (21613, 21)

In [17]:
print(f"Columns : {data.columns}")

Columns : Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

## Selecting Columns ##

In [24]:
# Access single column
column = data["price"]
print(column)

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64

In [31]:
# Access multiple columns
columns = data[["id","bedrooms","sqft_living"]]
print(columns)

               id  bedrooms  sqft_living
0      7129300520         3         1180
1      6414100192         3         2570
2      5631500400         2          770
3      2487200875         4         1960
4      1954400510         3         1680
...           ...       ...          ...
21608   263000018         3         1530
21609  6600060120         4         2310
21610  1523300141         2         1020
21611   291310100         3         1600
21612  1523300157         2         1020

[21613 rows x 3 columns]

## Filtering Columns ##

In [36]:
# Based on single condition
high_price = data[data["price"] <200000]
high_price

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,N,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
18,16000397,20141205T000000,189000.0,2,1.00,1200,9850,1.0,N,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
92,4168000060,20150226T000000,153000.0,3,1.00,1200,10500,1.0,N,0,...,7,1200,0,1962,0,98023,47.3220,-122.351,1350,10500
97,1099611230,20140912T000000,199000.0,4,1.50,1160,6400,1.0,N,0,...,7,1160,0,1975,0,98023,47.3036,-122.378,1160,6400
107,3530510041,20140723T000000,188500.0,2,1.75,1240,2493,1.0,N,0,...,8,1240,0,1985,0,98198,47.3813,-122.322,1270,4966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20403,6056100150,20140623T000000,160797.0,3,1.50,1270,2356,2.0,N,0,...,7,1270,0,2012,0,98108,47.5671,-122.298,1490,2175
20612,2724049222,20140802T000000,163800.0,2,2.50,1000,1092,2.0,N,0,...,7,990,10,2004,0,98118,47.5419,-122.271,1330,1466
20807,6056100160,20140728T000000,182568.0,4,1.50,1500,2106,2.0,N,0,...,7,1500,0,2014,0,98108,47.5669,-122.297,1490,2175
20962,1278000210,20150311T000000,110000.0,2,1.00,828,4524,1.0,N,0,...,6,828,0,1968,2007,98001,47.2655,-122.244,828,5402
20969,2781270530,20150326T000000,193000.0,2,1.75,910,2550,1.0,N,0,...,6,910,0,2004,0,98038,47.3494,-122.022,1310,2550

In [37]:
# Based on multiple conditions
f1 = data[(data["price"] < 200000 ) & (data["bedrooms"] > 3)]
f1

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
97,1099611230,20140912T000000,199000.0,4,1.50,1160,6400,1.0,N,0,...,7,1160,0,1975,0,98023,47.3036,-122.378,1160,6400
118,3454800060,20150108T000000,171800.0,4,2.00,1570,9600,1.0,N,0,...,6,1570,0,1950,0,98168,47.4965,-122.303,1880,9000
345,3969300030,20140723T000000,165000.0,4,1.00,1000,7134,1.0,N,0,...,6,1000,0,1943,0,98178,47.4897,-122.240,1020,7138
827,1610000016,20140911T000000,175000.0,4,1.00,1300,6030,1.5,N,0,...,6,1300,0,1947,0,98168,47.4778,-122.286,1240,6900
1737,5402100045,20150311T000000,189950.0,4,2.00,1910,4225,1.0,N,0,...,6,910,1000,1919,0,98001,47.3084,-122.234,1060,4800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19370,3353401340,20150216T000000,199900.0,4,1.75,1790,12000,1.0,N,0,...,6,1790,0,1944,0,98001,47.2664,-122.256,1550,9840
19458,1545807180,20150506T000000,190000.0,4,1.75,1900,9861,1.0,N,0,...,7,1900,0,1967,0,98038,47.3615,-122.057,1720,7967
19563,42000245,20140613T000000,171000.0,4,2.00,1520,19672,1.0,N,0,...,6,1020,500,1920,0,98188,47.4683,-122.281,1810,7840
19616,1446400564,20140507T000000,185000.0,4,1.00,1490,6600,1.0,N,0,...,7,1490,0,1969,0,98168,47.4835,-122.332,1280,6600
20807,6056100160,20140728T000000,182568.0,4,1.50,1500,2106,2.0,N,0,...,7,1500,0,2014,0,98108,47.5669,-122.297,1490,2175

<div style="background-color: #C3DEDD; padding: 10px; height: 100px; border-radius: 15px; position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha Dhiman <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>
    </div>
    <div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6;">
    <strong>📞 Connect @</strong><br>
    📧 Mail (Trisha Dhiman): <a href="mailto:dhimantrisha1812@gmail.com">dhimantrisha1812@gmail.com</a><br>
    📞 Contact: <a href="tel:+91-9729832340">+91-9729832340</a><br>
</div>
</div>

<br>